### PR TITLE
Kwaw kumi

### PR DESCRIPTION
**Pull request by Kay-kwaw**
I've just set up Supabase and started exploring its authentication services. I plan to dive deeper into it tomorrow.

### CODE REVIEW

**Review by OscarNii — COMMENTED** [review]
Masa is late here i need to sleep
Tomorrow we will continue 
haha

**Comment by Kay-kwaw** [comment]
Yes sir😂

**Comment by OscarNii** [comment]
Yo, when you go hit on the project again?
Wanted to add some features to the backend

**Comment by OscarNii** [comment]
senior @Kay-kwaw did you create an account for me or did you test out the signup page for authentication ??

**Comment by OscarNii** [comment]
> senior @Kay-kwaw did you create an account for me or did you test out the signup page for authentication ??

will you fix it or i should just go ahead and fix it right away

**Comment by Kay-kwaw** [comment]
creat an account for you as in?

**Comment by OscarNii** [comment]
Oh no no I meant I can’t sign in

**Pull request merged**
