### PR TITLE
Kwaw kumi

### PR DESCRIPTION
**Pull request by Kay-kwaw**
.dotenv file

### CODE REVIEW

**Comment by OscarNii** [comment]
Don't you think the SUPABASE_ANON_KEY is exposed in the .env file ??
I think it's a vulnerability

**Comment by OscarNii** [comment]
what do you think about that @Kay-kwaw ??

**Comment by Kay-kwaw** [comment]
Okay that’s fine, We can work on that.

**Comment by Kay-kwaw** [comment]
Yeah you’re right, it’s still exposed

**Pull request merged**
